export const SAVE_INPUT = "SAVE_INPUT";
export const SAVE_CHECKBOX = "SAVE_CHECKBOX";
export const RESET_CHECKBOXES = "RESET_CHECKBOXES";
export const FETCH_PLACES_SUCCESS = "FETCH_PLACES_SUCCESS";
export const SET_END_STATUS = "FETCH_END_STATUS";
export const DELETE_TRIP = "DELETE_TRIP";
export const DELETE_INPUT = "DELETE_INPUT";